"""WorldGuard public runtime API."""

from .contracts import (
    ClaimAtom,
    GuardContract,
    GuardPurposeContractBinding,
    claim_predictive_intent,
    derive_required_guards,
)
from .kernel import run_worldguard
from .mesh import ModelMeshContract, MeshReport, SemanticCoverageContract, run_model_mesh
from .reports import GuardResult, GuardedReport
from .semantic import (
    EXECUTOR_REGISTRY,
    NativeDepthReceipt,
    ProviderStatus,
    SemanticBinding,
    SemanticExecutionReceipt,
    SemanticStatus,
)
from .status import GuardStatus
from .template_packs import (
    BUILTIN_TEMPLATE_PARAMETER_TYPES,
    GUARD_CONTRACT_KIND,
    MODEL_MESH_CONTRACT_KIND,
    SKILLGUARD_TARGET_TEMPLATE_PROJECTION_FIELDS,
    SKILLGUARD_TARGET_TEMPLATE_PROJECTION_SCHEMA_VERSION,
    SKILLGUARD_TEMPLATE_CATALOG_FIELDS,
    SKILLGUARD_TEMPLATE_CATALOG_SCHEMA_VERSION,
    SKILLGUARD_TEMPLATE_MANIFEST_FIELDS,
    SKILLGUARD_TEMPLATE_MANIFEST_SCHEMA_VERSION,
    TemplateFragment,
    TemplateInstance,
    TemplateInstanceReceipt,
    TemplatePackError,
    TemplatePackManifest,
    TemplatePackRegistry,
    TemplateSelection,
    WORLDGUARD_TEMPLATE_NATIVE_OWNER_ID,
    WORLDGUARD_TEMPLATE_ROUTE_ID,
    build_template_instance,
    build_skillguard_target_template_projection,
    builtin_template_registry,
    compose_template_packs,
    resolve_template_slots,
    template_slot,
    validate_skillguard_target_template_projection,
)

__version__ = "0.1.2"

__all__ = [
    "__version__",
    "GuardContract",
    "GuardPurposeContractBinding",
    "ClaimAtom",
    "GuardResult",
    "GuardStatus",
    "GuardedReport",
    "MeshReport",
    "ModelMeshContract",
    "SemanticCoverageContract",
    "NativeDepthReceipt",
    "ProviderStatus",
    "SemanticBinding",
    "SemanticExecutionReceipt",
    "SemanticStatus",
    "EXECUTOR_REGISTRY",
    "run_model_mesh",
    "run_worldguard",
    "claim_predictive_intent",
    "derive_required_guards",
    "GUARD_CONTRACT_KIND",
    "MODEL_MESH_CONTRACT_KIND",
    "BUILTIN_TEMPLATE_PARAMETER_TYPES",
    "SKILLGUARD_TARGET_TEMPLATE_PROJECTION_FIELDS",
    "SKILLGUARD_TARGET_TEMPLATE_PROJECTION_SCHEMA_VERSION",
    "SKILLGUARD_TEMPLATE_CATALOG_FIELDS",
    "SKILLGUARD_TEMPLATE_CATALOG_SCHEMA_VERSION",
    "SKILLGUARD_TEMPLATE_MANIFEST_FIELDS",
    "SKILLGUARD_TEMPLATE_MANIFEST_SCHEMA_VERSION",
    "TemplateFragment",
    "TemplateInstance",
    "TemplateInstanceReceipt",
    "TemplatePackError",
    "TemplatePackManifest",
    "TemplatePackRegistry",
    "TemplateSelection",
    "WORLDGUARD_TEMPLATE_NATIVE_OWNER_ID",
    "WORLDGUARD_TEMPLATE_ROUTE_ID",
    "build_template_instance",
    "build_skillguard_target_template_projection",
    "builtin_template_registry",
    "compose_template_packs",
    "resolve_template_slots",
    "template_slot",
    "validate_skillguard_target_template_projection",
]
