"""WorldGuard public runtime API."""

from .contracts import (
    ClaimAtom,
    GuardContract,
    GuardPurposeContractBinding,
    claim_predictive_intent,
    derive_required_guards,
)
from .kernel import run_worldguard
from .mesh import ModelMeshContract, MeshReport, SemanticCoverageContract, run_model_mesh
from .reports import GuardResult, GuardedReport
from .semantic import (
    EXECUTOR_REGISTRY,
    NativeDepthReceipt,
    ProviderStatus,
    SemanticBinding,
    SemanticExecutionReceipt,
    SemanticStatus,
)
from .status import GuardStatus
from .task_local_revision import (
    CandidateWorldModelRevision,
    ExpectedWorldRelationship,
    ExpectedWorldValue,
    ObservedWorldRelationship,
    ObservedWorldSnapshot,
    PredictionSnapshot,
    RevalidationRole,
    WorldMismatchCategory,
    WorldModelIdentity,
    WorldRevisionKind,
    WorldRevalidationReceipt,
    compare_observed_world,
    evaluate_candidate_world_revision,
    freeze_prediction_snapshot,
)
from .template_packs import (
    BUILTIN_TEMPLATE_PARAMETER_TYPES,
    GUARD_CONTRACT_KIND,
    MODEL_MESH_CONTRACT_KIND,
    TARGET_TEMPLATE_INTERCHANGE_FIELDS,
    TARGET_TEMPLATE_INTERCHANGE_SCHEMA_VERSION,
    TARGET_TEMPLATE_CATALOG_FIELDS,
    TARGET_TEMPLATE_CATALOG_SCHEMA_VERSION,
    TARGET_TEMPLATE_MANIFEST_FIELDS,
    TARGET_TEMPLATE_MANIFEST_SCHEMA_VERSION,
    TemplateFragment,
    TemplateInstance,
    TemplateInstanceReceipt,
    TemplatePackError,
    TemplatePackManifest,
    TemplatePackRegistry,
    TemplateSelection,
    WORLDGUARD_TEMPLATE_NATIVE_OWNER_ID,
    WORLDGUARD_TEMPLATE_ROUTE_ID,
    build_template_instance,
    build_target_template_interchange,
    builtin_template_registry,
    compose_template_packs,
    resolve_template_slots,
    template_slot,
    validate_target_template_interchange,
)

__version__ = "0.4.1"

__all__ = [
    "__version__",
    "GuardContract",
    "GuardPurposeContractBinding",
    "ClaimAtom",
    "GuardResult",
    "GuardStatus",
    "GuardedReport",
    "MeshReport",
    "ModelMeshContract",
    "SemanticCoverageContract",
    "NativeDepthReceipt",
    "ProviderStatus",
    "SemanticBinding",
    "SemanticExecutionReceipt",
    "SemanticStatus",
    "EXECUTOR_REGISTRY",
    "run_model_mesh",
    "run_worldguard",
    "CandidateWorldModelRevision",
    "ExpectedWorldRelationship",
    "ExpectedWorldValue",
    "ObservedWorldRelationship",
    "ObservedWorldSnapshot",
    "PredictionSnapshot",
    "RevalidationRole",
    "WorldMismatchCategory",
    "WorldModelIdentity",
    "WorldRevisionKind",
    "WorldRevalidationReceipt",
    "compare_observed_world",
    "evaluate_candidate_world_revision",
    "freeze_prediction_snapshot",
    "claim_predictive_intent",
    "derive_required_guards",
    "GUARD_CONTRACT_KIND",
    "MODEL_MESH_CONTRACT_KIND",
    "BUILTIN_TEMPLATE_PARAMETER_TYPES",
    "TARGET_TEMPLATE_INTERCHANGE_FIELDS",
    "TARGET_TEMPLATE_INTERCHANGE_SCHEMA_VERSION",
    "TARGET_TEMPLATE_CATALOG_FIELDS",
    "TARGET_TEMPLATE_CATALOG_SCHEMA_VERSION",
    "TARGET_TEMPLATE_MANIFEST_FIELDS",
    "TARGET_TEMPLATE_MANIFEST_SCHEMA_VERSION",
    "TemplateFragment",
    "TemplateInstance",
    "TemplateInstanceReceipt",
    "TemplatePackError",
    "TemplatePackManifest",
    "TemplatePackRegistry",
    "TemplateSelection",
    "WORLDGUARD_TEMPLATE_NATIVE_OWNER_ID",
    "WORLDGUARD_TEMPLATE_ROUTE_ID",
    "build_template_instance",
    "build_target_template_interchange",
    "builtin_template_registry",
    "compose_template_packs",
    "resolve_template_slots",
    "template_slot",
    "validate_target_template_interchange",
]
